package com.social.platform.SocialMediaAPI.controller;

import com.social.platform.SocialMediaAPI.entity.Comments;
import com.social.platform.SocialMediaAPI.service.CommentsService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

import java.util.UUID;

/**
 * REST Controller for Comments entity
 * Generated by MDE Backend Generator
 */
@RestController
@RequestMapping("/api/comments")
@CrossOrigin(origins = "*")
public class CommentsController {

    private final CommentsService service;

    public CommentsController(CommentsService service) {
        this.service = service;
    }

    /**
     * Create a new Comments
     * POST /api/comments
     */
    @PostMapping
    public ResponseEntity<Comments> create(@RequestBody Comments entity) {
        Comments created = service.create(entity);
        return new ResponseEntity<>(created, HttpStatus.CREATED);
    }

    /**
     * Get Comments by ID
     * GET /api/comments/{id}
     */
    @GetMapping("/{id}")
    public ResponseEntity<Comments> getById(@PathVariable UUID id) {
        return service.findById(id)
                .map(entity -> new ResponseEntity<>(entity, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Get all Comments entities
     * GET /api/comments
     */
    @GetMapping
    public ResponseEntity<List<Comments>> getAll() {
        List<Comments> entities = service.findAll();
        return new ResponseEntity<>(entities, HttpStatus.OK);
    }

    /**
     * Update an existing Comments
     * PUT /api/comments/{id}
     */
    @PutMapping("/{id}")
    public ResponseEntity<Comments> update(
            @PathVariable UUID id,
            @RequestBody Comments entity) {
        try {
            Comments updated = service.update(id, entity);
            return new ResponseEntity<>(updated, HttpStatus.OK);
        } catch (RuntimeException e) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
    }

    /**
     * Delete Comments by ID
     * DELETE /api/comments/{id}
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable UUID id) {
        if (!service.exists(id)) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
        service.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }
}
