package com.social.platform.SocialMediaAPI.controller;

import com.social.platform.SocialMediaAPI.entity.DirectMessages;
import com.social.platform.SocialMediaAPI.service.DirectMessagesService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

import java.util.UUID;

/**
 * REST Controller for DirectMessages entity
 * Generated by MDE Backend Generator
 */
@RestController
@RequestMapping("/api/direct_messages")
@CrossOrigin(origins = "*")
public class DirectMessagesController {

    private final DirectMessagesService service;

    public DirectMessagesController(DirectMessagesService service) {
        this.service = service;
    }

    /**
     * Create a new DirectMessages
     * POST /api/direct_messages
     */
    @PostMapping
    public ResponseEntity<DirectMessages> create(@RequestBody DirectMessages entity) {
        DirectMessages created = service.create(entity);
        return new ResponseEntity<>(created, HttpStatus.CREATED);
    }

    /**
     * Get DirectMessages by ID
     * GET /api/direct_messages/{id}
     */
    @GetMapping("/{id}")
    public ResponseEntity<DirectMessages> getById(@PathVariable UUID id) {
        return service.findById(id)
                .map(entity -> new ResponseEntity<>(entity, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Get all DirectMessages entities
     * GET /api/direct_messages
     */
    @GetMapping
    public ResponseEntity<List<DirectMessages>> getAll() {
        List<DirectMessages> entities = service.findAll();
        return new ResponseEntity<>(entities, HttpStatus.OK);
    }

    /**
     * Update an existing DirectMessages
     * PUT /api/direct_messages/{id}
     */
    @PutMapping("/{id}")
    public ResponseEntity<DirectMessages> update(
            @PathVariable UUID id,
            @RequestBody DirectMessages entity) {
        try {
            DirectMessages updated = service.update(id, entity);
            return new ResponseEntity<>(updated, HttpStatus.OK);
        } catch (RuntimeException e) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
    }

    /**
     * Delete DirectMessages by ID
     * DELETE /api/direct_messages/{id}
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable UUID id) {
        if (!service.exists(id)) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
        service.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }
}
