package com.social.platform.SocialMediaAPI.controller;

import com.social.platform.SocialMediaAPI.entity.Hashtags;
import com.social.platform.SocialMediaAPI.service.HashtagsService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

import java.util.UUID;

/**
 * REST Controller for Hashtags entity
 * Generated by MDE Backend Generator
 */
@RestController
@RequestMapping("/api/hashtags")
@CrossOrigin(origins = "*")
public class HashtagsController {

    private final HashtagsService service;

    public HashtagsController(HashtagsService service) {
        this.service = service;
    }

    /**
     * Create a new Hashtags
     * POST /api/hashtags
     */
    @PostMapping
    public ResponseEntity<Hashtags> create(@RequestBody Hashtags entity) {
        Hashtags created = service.create(entity);
        return new ResponseEntity<>(created, HttpStatus.CREATED);
    }

    /**
     * Get Hashtags by ID
     * GET /api/hashtags/{id}
     */
    @GetMapping("/{id}")
    public ResponseEntity<Hashtags> getById(@PathVariable UUID id) {
        return service.findById(id)
                .map(entity -> new ResponseEntity<>(entity, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Get all Hashtags entities
     * GET /api/hashtags
     */
    @GetMapping
    public ResponseEntity<List<Hashtags>> getAll() {
        List<Hashtags> entities = service.findAll();
        return new ResponseEntity<>(entities, HttpStatus.OK);
    }

    /**
     * Update an existing Hashtags
     * PUT /api/hashtags/{id}
     */
    @PutMapping("/{id}")
    public ResponseEntity<Hashtags> update(
            @PathVariable UUID id,
            @RequestBody Hashtags entity) {
        try {
            Hashtags updated = service.update(id, entity);
            return new ResponseEntity<>(updated, HttpStatus.OK);
        } catch (RuntimeException e) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
    }

    /**
     * Delete Hashtags by ID
     * DELETE /api/hashtags/{id}
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable UUID id) {
        if (!service.exists(id)) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
        service.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }
}
