package com.social.platform.SocialMediaAPI.controller;

import com.social.platform.SocialMediaAPI.entity.Likes;
import com.social.platform.SocialMediaAPI.service.LikesService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

import java.util.UUID;

/**
 * REST Controller for Likes entity
 * Generated by MDE Backend Generator
 */
@RestController
@RequestMapping("/api/likes")
@CrossOrigin(origins = "*")
public class LikesController {

    private final LikesService service;

    public LikesController(LikesService service) {
        this.service = service;
    }

    /**
     * Create a new Likes
     * POST /api/likes
     */
    @PostMapping
    public ResponseEntity<Likes> create(@RequestBody Likes entity) {
        Likes created = service.create(entity);
        return new ResponseEntity<>(created, HttpStatus.CREATED);
    }

    /**
     * Get Likes by ID
     * GET /api/likes/{id}
     */
    @GetMapping("/{id}")
    public ResponseEntity<Likes> getById(@PathVariable UUID id) {
        return service.findById(id)
                .map(entity -> new ResponseEntity<>(entity, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Get all Likes entities
     * GET /api/likes
     */
    @GetMapping
    public ResponseEntity<List<Likes>> getAll() {
        List<Likes> entities = service.findAll();
        return new ResponseEntity<>(entities, HttpStatus.OK);
    }

    /**
     * Update an existing Likes
     * PUT /api/likes/{id}
     */
    @PutMapping("/{id}")
    public ResponseEntity<Likes> update(
            @PathVariable UUID id,
            @RequestBody Likes entity) {
        try {
            Likes updated = service.update(id, entity);
            return new ResponseEntity<>(updated, HttpStatus.OK);
        } catch (RuntimeException e) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
    }

    /**
     * Delete Likes by ID
     * DELETE /api/likes/{id}
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable UUID id) {
        if (!service.exists(id)) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
        service.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }
}
