package com.social.platform.SocialMediaAPI.controller;

import com.social.platform.SocialMediaAPI.entity.Notifications;
import com.social.platform.SocialMediaAPI.service.NotificationsService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

import java.util.UUID;

/**
 * REST Controller for Notifications entity
 * Generated by MDE Backend Generator
 */
@RestController
@RequestMapping("/api/notifications")
@CrossOrigin(origins = "*")
public class NotificationsController {

    private final NotificationsService service;

    public NotificationsController(NotificationsService service) {
        this.service = service;
    }

    /**
     * Create a new Notifications
     * POST /api/notifications
     */
    @PostMapping
    public ResponseEntity<Notifications> create(@RequestBody Notifications entity) {
        Notifications created = service.create(entity);
        return new ResponseEntity<>(created, HttpStatus.CREATED);
    }

    /**
     * Get Notifications by ID
     * GET /api/notifications/{id}
     */
    @GetMapping("/{id}")
    public ResponseEntity<Notifications> getById(@PathVariable UUID id) {
        return service.findById(id)
                .map(entity -> new ResponseEntity<>(entity, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Get all Notifications entities
     * GET /api/notifications
     */
    @GetMapping
    public ResponseEntity<List<Notifications>> getAll() {
        List<Notifications> entities = service.findAll();
        return new ResponseEntity<>(entities, HttpStatus.OK);
    }

    /**
     * Update an existing Notifications
     * PUT /api/notifications/{id}
     */
    @PutMapping("/{id}")
    public ResponseEntity<Notifications> update(
            @PathVariable UUID id,
            @RequestBody Notifications entity) {
        try {
            Notifications updated = service.update(id, entity);
            return new ResponseEntity<>(updated, HttpStatus.OK);
        } catch (RuntimeException e) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
    }

    /**
     * Delete Notifications by ID
     * DELETE /api/notifications/{id}
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable UUID id) {
        if (!service.exists(id)) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
        service.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }
}
