package com.social.platform.SocialMediaAPI.controller;

import com.social.platform.SocialMediaAPI.entity.PostHashtags;
import com.social.platform.SocialMediaAPI.service.PostHashtagsService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

import java.util.UUID;

/**
 * REST Controller for PostHashtags entity
 * Generated by MDE Backend Generator
 */
@RestController
@RequestMapping("/api/post_hashtags")
@CrossOrigin(origins = "*")
public class PostHashtagsController {

    private final PostHashtagsService service;

    public PostHashtagsController(PostHashtagsService service) {
        this.service = service;
    }

    /**
     * Create a new PostHashtags
     * POST /api/post_hashtags
     */
    @PostMapping
    public ResponseEntity<PostHashtags> create(@RequestBody PostHashtags entity) {
        PostHashtags created = service.create(entity);
        return new ResponseEntity<>(created, HttpStatus.CREATED);
    }

    /**
     * Get PostHashtags by ID
     * GET /api/post_hashtags/{id}
     */
    @GetMapping("/{id}")
    public ResponseEntity<PostHashtags> getById(@PathVariable UUID id) {
        return service.findById(id)
                .map(entity -> new ResponseEntity<>(entity, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Get all PostHashtags entities
     * GET /api/post_hashtags
     */
    @GetMapping
    public ResponseEntity<List<PostHashtags>> getAll() {
        List<PostHashtags> entities = service.findAll();
        return new ResponseEntity<>(entities, HttpStatus.OK);
    }

    /**
     * Update an existing PostHashtags
     * PUT /api/post_hashtags/{id}
     */
    @PutMapping("/{id}")
    public ResponseEntity<PostHashtags> update(
            @PathVariable UUID id,
            @RequestBody PostHashtags entity) {
        try {
            PostHashtags updated = service.update(id, entity);
            return new ResponseEntity<>(updated, HttpStatus.OK);
        } catch (RuntimeException e) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
    }

    /**
     * Delete PostHashtags by ID
     * DELETE /api/post_hashtags/{id}
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable UUID id) {
        if (!service.exists(id)) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
        service.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }
}
