package com.social.platform.SocialMediaAPI.controller;

import com.social.platform.SocialMediaAPI.entity.Posts;
import com.social.platform.SocialMediaAPI.service.PostsService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

import java.util.UUID;

/**
 * REST Controller for Posts entity
 * Generated by MDE Backend Generator
 */
@RestController
@RequestMapping("/api/posts")
@CrossOrigin(origins = "*")
public class PostsController {

    private final PostsService service;

    public PostsController(PostsService service) {
        this.service = service;
    }

    /**
     * Create a new Posts
     * POST /api/posts
     */
    @PostMapping
    public ResponseEntity<Posts> create(@RequestBody Posts entity) {
        Posts created = service.create(entity);
        return new ResponseEntity<>(created, HttpStatus.CREATED);
    }

    /**
     * Get Posts by ID
     * GET /api/posts/{id}
     */
    @GetMapping("/{id}")
    public ResponseEntity<Posts> getById(@PathVariable UUID id) {
        return service.findById(id)
                .map(entity -> new ResponseEntity<>(entity, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Get all Posts entities
     * GET /api/posts
     */
    @GetMapping
    public ResponseEntity<List<Posts>> getAll() {
        List<Posts> entities = service.findAll();
        return new ResponseEntity<>(entities, HttpStatus.OK);
    }

    /**
     * Update an existing Posts
     * PUT /api/posts/{id}
     */
    @PutMapping("/{id}")
    public ResponseEntity<Posts> update(
            @PathVariable UUID id,
            @RequestBody Posts entity) {
        try {
            Posts updated = service.update(id, entity);
            return new ResponseEntity<>(updated, HttpStatus.OK);
        } catch (RuntimeException e) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
    }

    /**
     * Delete Posts by ID
     * DELETE /api/posts/{id}
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable UUID id) {
        if (!service.exists(id)) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
        service.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }
}
