package com.social.platform.SocialMediaAPI.controller;

import com.social.platform.SocialMediaAPI.entity.UserFollows;
import com.social.platform.SocialMediaAPI.service.UserFollowsService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

import java.util.UUID;

/**
 * REST Controller for UserFollows entity
 * Generated by MDE Backend Generator
 */
@RestController
@RequestMapping("/api/user_follows")
@CrossOrigin(origins = "*")
public class UserFollowsController {

    private final UserFollowsService service;

    public UserFollowsController(UserFollowsService service) {
        this.service = service;
    }

    /**
     * Create a new UserFollows
     * POST /api/user_follows
     */
    @PostMapping
    public ResponseEntity<UserFollows> create(@RequestBody UserFollows entity) {
        UserFollows created = service.create(entity);
        return new ResponseEntity<>(created, HttpStatus.CREATED);
    }

    /**
     * Get UserFollows by ID
     * GET /api/user_follows/{id}
     */
    @GetMapping("/{id}")
    public ResponseEntity<UserFollows> getById(@PathVariable UUID id) {
        return service.findById(id)
                .map(entity -> new ResponseEntity<>(entity, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Get all UserFollows entities
     * GET /api/user_follows
     */
    @GetMapping
    public ResponseEntity<List<UserFollows>> getAll() {
        List<UserFollows> entities = service.findAll();
        return new ResponseEntity<>(entities, HttpStatus.OK);
    }

    /**
     * Update an existing UserFollows
     * PUT /api/user_follows/{id}
     */
    @PutMapping("/{id}")
    public ResponseEntity<UserFollows> update(
            @PathVariable UUID id,
            @RequestBody UserFollows entity) {
        try {
            UserFollows updated = service.update(id, entity);
            return new ResponseEntity<>(updated, HttpStatus.OK);
        } catch (RuntimeException e) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
    }

    /**
     * Delete UserFollows by ID
     * DELETE /api/user_follows/{id}
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable UUID id) {
        if (!service.exists(id)) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
        service.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }
}
