version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing OWASP ZAP for DAST scanning...
      - export LANG=en_US.UTF-8
      - export LC_ALL=en_US.UTF-8
      - export PYTHONIOENCODING=utf-8
      - apt-get update
      - apt-get install -y wget default-jdk jq
      - wget https://github.com/zaproxy/zaproxy/releases/download/v2.16.1/ZAP_2.16.1_Linux.tar.gz
      - tar -xvf ZAP_2.16.1_Linux.tar.gz
      - echo Scaling up staging environment for DAST testing...
      - aws ecs update-service --cluster social-media-api-staging --service social-media-api-staging-service --desired-count 1 --region eu-west-3
      - echo "Waiting for staging service to stabilize (up to ~5m)..."
      - aws ecs wait services-stable --cluster social-media-api-staging --services social-media-api-staging-service --region eu-west-3 || true
      - echo Discovering staging application endpoint via ECS...
      - |
        # Get running task from ECS service
        TASK_ARN=$(aws ecs list-tasks \
          --cluster social-media-api-staging \
          --service-name social-media-api-staging-service \
          --desired-status RUNNING \
          --region eu-west-3 \
          --query 'taskArns[0]' \
          --output text)
        
        # Retry to wait for running task (up to ~5 minutes) and print debug info
        RETRIES=30
        INTERVAL=10
        COUNT=0
        while [ -z "$TASK_ARN" ] || [ "$TASK_ARN" = "None" ] 2>/dev/null; do
          if [ "$COUNT" -ge "$RETRIES" ]; then
            echo "ERROR: No running task found in staging service after $((RETRIES*INTERVAL))s"
            echo "Last raw output of aws ecs list-tasks:"
            aws ecs list-tasks \
              --cluster social-media-api-staging \
              --service-name social-media-api-staging-service \
              --desired-status RUNNING \
              --region eu-west-3 \
              --output json || true
            exit 1
          fi
          echo "No running task yet, retrying in $INTERVAL seconds... ($COUNT/$RETRIES)"
          sleep $INTERVAL
          # Print the raw output each attempt to help diagnose timing/permission issues
          TASKS_RAW=$(aws ecs list-tasks \
            --cluster social-media-api-staging \
            --service-name social-media-api-staging-service \
            --desired-status RUNNING \
            --region eu-west-3 \
            --output json) || TASKS_RAW=""
          echo "list-tasks raw: $TASKS_RAW"
          TASK_ARN=$(echo "$TASKS_RAW" | jq -r '.taskArns[0] // ""')
          COUNT=$((COUNT+1))
        done
        echo "Found running task: $TASK_ARN"
        
        # Get container instance ARN from task
        CONTAINER_INSTANCE_ARN=$(aws ecs describe-tasks \
          --cluster social-media-api-staging \
          --tasks $TASK_ARN \
          --region eu-west-3 \
          --query 'tasks[0].containerInstanceArn' \
          --output text)
        
        echo "Container instance: $CONTAINER_INSTANCE_ARN"

        # Determine whether task runs on EC2 (container instance) or Fargate (no containerInstanceArn)
        if [ -z "$CONTAINER_INSTANCE_ARN" ] || [ "$CONTAINER_INSTANCE_ARN" = "None" ]; then
          echo "Task appears to be running on Fargate or no container instance attached. Attempting to discover ENI public IP..."
          ENI_ID=$(aws ecs describe-tasks \
            --cluster social-media-api-staging \
            --tasks $TASK_ARN \
            --region eu-west-3 \
            --query "tasks[0].attachments[0].details[?name=='networkInterfaceId'].value" \
            --output text)

          echo "Found ENI: $ENI_ID"

          if [ -z "$ENI_ID" ] || [ "$ENI_ID" = "None" ]; then
            echo "ERROR: Could not find network interface id for Fargate task. Ensure service is using awsvpc and ENI is available."
            exit 1
          fi

          STAGING_IP=$(aws ec2 describe-network-interfaces \
            --network-interface-ids $ENI_ID \
            --region eu-west-3 \
            --query 'NetworkInterfaces[0].Association.PublicIp' \
            --output text)

          if [ -z "$STAGING_IP" ] || [ "$STAGING_IP" = "None" ]; then
            echo "No Public IP found on ENI. Trying private IP..."
            STAGING_IP=$(aws ec2 describe-network-interfaces \
              --network-interface-ids $ENI_ID \
              --region eu-west-3 \
              --query 'NetworkInterfaces[0].PrivateIpAddress' \
              --output text)
            echo "Discovered private IP: $STAGING_IP (DAST requires a routable public IP or ALB)"
          fi
        else
          # Get EC2 instance ID from container instance
          EC2_INSTANCE_ID=$(aws ecs describe-container-instances \
            --cluster social-media-api-staging \
            --container-instances $CONTAINER_INSTANCE_ARN \
            --region eu-west-3 \
            --query 'containerInstances[0].ec2InstanceId' \
            --output text)

          echo "EC2 instance: $EC2_INSTANCE_ID"

          # Get public IP of EC2 instance
          STAGING_IP=$(aws ec2 describe-instances \
            --instance-ids $EC2_INSTANCE_ID \
            --region eu-west-3 \
            --query 'Reservations[0].Instances[0].PublicIpAddress' \
            --output text)
        fi

        if [ "$STAGING_IP" = "None" ] || [ -z "$STAGING_IP" ]; then
          echo "ERROR: Could not retrieve a usable IP address for staging task. Ensure the task has a public IP or expose the app via an ALB."
          exit 1
        fi

        export STAGING_URL="http://${STAGING_IP}:8080"
        echo "Staging application auto-discovered at: $STAGING_URL"
      
  build:
    commands:
      - echo Running FULL DAST scan on `date`
      - echo Target URL is $STAGING_URL
      - cd ZAP_2.16.1
      
      # Full automated scan (spider + active scan) instead of quickscan
      # This will take 15-30 minutes but finds MUCH more
      - echo Starting comprehensive ZAP scan...
      - |
        ./zap.sh \
          -host 0.0.0.0 -port 8090 -daemon \
          -config api.disablekey=true \
          -config spider.maxDuration=10 \
          -config scanner.maxRuleDurationInMins=10 &
        
        ZAP_PID=$!
        echo "ZAP daemon started with PID $ZAP_PID"
        sleep 30
      
      # Spider the application (discover all endpoints)
      - |
        echo "Spidering application..."
        curl "http://localhost:8090/JSON/spider/action/scan/?url=$STAGING_URL&maxChildren=10" || true
        sleep 10
        
        # Wait for spider to complete
        while [ $(curl -s "http://localhost:8090/JSON/spider/view/status/" | grep -o '"status":"[0-9]*"' | grep -o '[0-9]*') -lt 100 ] 2>/dev/null; do
          echo "Spider progress: $(curl -s "http://localhost:8090/JSON/spider/view/status/" | grep -o '[0-9]*')%"
          sleep 5
        done
        echo "Spider completed!"
      
      # Active scan for vulnerabilities
      - |
        echo "Running active security scan..."
        curl "http://localhost:8090/JSON/ascan/action/scan/?url=$STAGING_URL&recurse=true&inScopeOnly=false" || true
        sleep 10
        
        # Wait for active scan to complete
        while [ $(curl -s "http://localhost:8090/JSON/ascan/view/status/" | grep -o '"status":"[0-9]*"' | grep -o '[0-9]*') -lt 100 ] 2>/dev/null; do
          PROGRESS=$(curl -s "http://localhost:8090/JSON/ascan/view/status/" | grep -o '[0-9]*')
          echo "Active scan progress: $PROGRESS%"
          sleep 10
        done
        echo "Active scan completed!"
      
      # Generate reports
      - |
        echo "Generating reports..."
        BUILD_DIR=$(echo /codebuild/output/src*)
        curl "http://localhost:8090/OTHER/core/other/htmlreport/" -o "$BUILD_DIR/zap-report.html" || true
        curl "http://localhost:8090/JSON/core/view/alerts/" -o "$BUILD_DIR/zap-report.json" || true
        # Get alerts summary
        ALERTS=$(curl -s "http://localhost:8090/JSON/core/view/numberOfAlerts/" | grep -o '[0-9]*' || echo "0")
        echo "Total alerts found: $ALERTS"
        
        # Fail if critical/high vulnerabilities found
        HIGH_ALERTS=$(curl -s "http://localhost:8090/JSON/core/view/alertsSummary/" | grep -o '"High":[0-9]*' | grep -o '[0-9]*' || echo "0")
        if [ "$HIGH_ALERTS" -gt 0 ]; then
          echo "ERROR: Found $HIGH_ALERTS high-severity vulnerabilities!"
          exit 1
        fi
      
      
  post_build:
    commands:
      - echo DAST scan completed on `date`
      - echo Uploading DAST reports to S3...
      - cd /codebuild/output/src*/
      - aws s3 cp zap-report.html s3://$REPORTS_BUCKET/dast-reports/$CODEBUILD_BUILD_NUMBER/zap-report.html --region eu-west-3
      - aws s3 cp zap-report.json s3://$REPORTS_BUCKET/dast-reports/$CODEBUILD_BUILD_NUMBER/zap-report.json --region eu-west-3 || true
      - echo Scaling down staging environment to save costs...
      - aws ecs update-service --cluster social-media-api-staging --service social-media-api-staging-service --desired-count 0 --region eu-west-3

artifacts:
  files:
    - zap-report.html
    - zap-report.json
