version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing SAST tools...
      - echo Downloading and installing Semgrep for SAST scanning
      - pip3 install semgrep
      
  build:
    commands:
      - echo Running SAST scan on `date`
      - semgrep --config=auto --json --output=semgrep-report.json src/ || true
      - semgrep --config=auto --sarif --output=semgrep-report.sarif src/ || true
      
  post_build:
    commands:
      - echo SAST scan completed on `date`
      - echo Uploading SAST reports to S3...
      - aws s3 cp semgrep-report.json s3://$REPORTS_BUCKET/sast-reports/$CODEBUILD_BUILD_NUMBER/semgrep-report.json --region eu-west-3
      - aws s3 cp semgrep-report.sarif s3://$REPORTS_BUCKET/sast-reports/$CODEBUILD_BUILD_NUMBER/semgrep-report.sarif --region eu-west-3
      - echo SAST scan results uploaded

artifacts:
  files:
    - semgrep-report.json
    - semgrep-report.sarif
