version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing OWASP ZAP for DAST scanning...
      - apt-get update
      - apt-get install -y wget default-jdk
      - wget https://github.com/zaproxy/zaproxy/releases/download/v2.16.1/ZAP_2.16.1_Linux.tar.gz
      - tar -xvf ZAP_2.16.1_Linux.tar.gz
      
  build:
    commands:
      - echo Running DAST scan on `date`
      - echo Target URL is $STAGING_URL
      - cd ZAP_2.16.1
      - ./zap.sh -cmd -quickurl $STAGING_URL -quickout ../zap-report.html -quickprogress || true
      - ./zap.sh -cmd -quickurl $STAGING_URL -quickout ../zap-report.json -quickprogress -quickjson || true
      
  post_build:
    commands:
      - echo DAST scan completed on `date`
      - echo Uploading DAST reports to S3...
      - cd ..
      - aws s3 cp zap-report.html s3://$REPORTS_BUCKET/dast-reports/$CODEBUILD_BUILD_NUMBER/zap-report.html --region eu-west-3
      - aws s3 cp zap-report.json s3://$REPORTS_BUCKET/dast-reports/$CODEBUILD_BUILD_NUMBER/zap-report.json --region eu-west-3 || true

artifacts:
  files:
    - zap-report.html
    - zap-report.json
