version: 0.2

# Gitleaks will automatically scan:
# - Git commit history for secrets
# - All source files for API keys, passwords, tokens
# - Configuration files (application.properties, yml)
# - Detects 1000+ secret patterns (AWS, GitHub, Slack, DB credentials, etc.)

phases:
  install:
    commands:
      - echo Installing Gitleaks for secrets scanning...
      - wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.4/gitleaks_8.18.4_linux_x64.tar.gz
      - tar -xzf gitleaks_8.18.4_linux_x64.tar.gz
      - chmod +x gitleaks
      - mv gitleaks /usr/local/bin/
      
  build:
    commands:
      - echo Running Gitleaks secrets scan on `date`
      - echo Scanning entire git history and all files...
      
      # Scan for secrets in entire repo
      - |
        gitleaks detect \
          --source . \
          --report-format json \
          --report-path gitleaks-report.json \
          --verbose \
          --exit-code 1 || GITLEAKS_EXIT=$?
      
      # Generate summary
      - |
        if [ -f gitleaks-report.json ]; then
          SECRETS_COUNT=$(cat gitleaks-report.json | grep -o '"Secret":' | wc -l)
          echo "Found $SECRETS_COUNT secrets!"
          
          cat > gitleaks-summary.json << EOF
        {
          "scan_date": "$(date -Iseconds)",
          "secrets_found": $SECRETS_COUNT,
          "status": "$([ $SECRETS_COUNT -gt 0 ] && echo 'FAILED' || echo 'PASSED')",
          "severity": "$([ $SECRETS_COUNT -gt 0 ] && echo 'CRITICAL' || echo 'NONE')"
        }
        EOF
        else
          echo "No secrets detected"
          cat > gitleaks-summary.json << EOF
        {
          "scan_date": "$(date -Iseconds)",
          "secrets_found": 0,
          "status": "PASSED",
          "severity": "NONE"
        }
        EOF
        fi
      
      - cat gitleaks-summary.json
      
      # Fail build if secrets found
      - |
        if [ "${GITLEAKS_EXIT:-0}" -eq 1 ]; then
          echo "ERROR: Secrets detected! Build failed."
          exit 1
        fi
      
  post_build:
    commands:
      - echo Gitleaks scan completed on `date`
      - echo Uploading secrets reports to S3...
      - aws s3 cp gitleaks-report.json s3://$REPORTS_BUCKET/secrets-reports/$CODEBUILD_BUILD_NUMBER/gitleaks-report.json --region eu-west-3 || true
      - aws s3 cp gitleaks-summary.json s3://$REPORTS_BUCKET/secrets-reports/$CODEBUILD_BUILD_NUMBER/gitleaks-summary.json --region eu-west-3 || true

artifacts:
  files:
    - gitleaks-report.json
    - gitleaks-summary.json
