version: 0.2

# SpotBugs + OWASP Dependency-Check will detect:
# - Hardcoded credentials
# - Missing input validation
# - SQL injection risks
# - Security vulnerabilities in code
# - CVEs in dependencies (spring-boot, postgres, etc.)
# - Insecure configurations
# - Common Java bugs and anti-patterns

phases:
  pre_build:
    commands:
      - echo Installing Java security analysis tools...
      - apt-get update
      - apt-get install -y openjdk-17-jdk wget
      
  build:
    commands:
      - echo Running SpotBugs security analysis on `date`
      - echo Building project with SpotBugs...
      - |
        mvn clean compile spotbugs:spotbugs \
          -Dspotbugs.effort=Max \
          -Dspotbugs.threshold=Low \
          -Dspotbugs.xmlOutput=true \
          -Dspotbugs.xmlOutputDirectory=target
      
      - echo Running OWASP Dependency-Check for CVEs...
      - |
        mvn org.owasp:dependency-check-maven:check \
          -DfailBuildOnCVSS=7 \
          -DsuppressionFiles=dependency-check-suppressions.xml \
          -DnvdApiKey=none || true
      
      - echo Analyzing results...
      - |
        # Count SpotBugs issues
        if [ -f target/spotbugsXml.xml ]; then
          BUGS=$(grep -c "<BugInstance" target/spotbugsXml.xml || echo "0")
          echo "SpotBugs found $BUGS potential issues"
          
          # Fail on high/medium priority bugs
          HIGH_BUGS=$(grep -c 'priority="1"' target/spotbugsXml.xml || echo "0")
          if [ "$HIGH_BUGS" -gt 0 ]; then
            echo "ERROR: Found $HIGH_BUGS high-priority bugs!"
            exit 1
          fi
        fi
      
      - |
        # Check dependency vulnerabilities
        if [ -f target/dependency-check-report.json ]; then
          CVE_COUNT=$(grep -c '"severity"' target/dependency-check-report.json || echo "0")
          echo "Found $CVE_COUNT dependency vulnerabilities"
        fi
      
  post_build:
    commands:
      - echo Code quality analysis completed on `date`
      - echo Uploading reports to S3...
      - aws s3 cp target/spotbugsXml.xml s3://$REPORTS_BUCKET/code-quality-reports/$CODEBUILD_BUILD_NUMBER/spotbugs.xml --region eu-west-3 || true
      - aws s3 cp target/dependency-check-report.html s3://$REPORTS_BUCKET/code-quality-reports/$CODEBUILD_BUILD_NUMBER/dependency-check.html --region eu-west-3 || true
      - aws s3 cp target/dependency-check-report.json s3://$REPORTS_BUCKET/code-quality-reports/$CODEBUILD_BUILD_NUMBER/dependency-check.json --region eu-west-3 || true

artifacts:
  files:
    - target/spotbugsXml.xml
    - target/dependency-check-report.html
    - target/dependency-check-report.json
