version: 0.2

# Fast CVE scanning with Grype (Anchore)
# Lightweight, no database downloads, works offline
# Scans: JARs, dependencies, Docker images

phases:
  pre_build:
    commands:
      - echo Installing Grype CVE scanner...
      - curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
      
  build:
    commands:
      - echo Running Grype CVE scan on `date`
      - |
        # Scan pom.xml for Maven dependencies
        grype pom.xml --output json --file grype-report.json || echo "Grype scan completed with warnings"
        
        # Generate HTML report
        grype pom.xml --output table > grype-report.txt || true
        
        # Count vulnerabilities
        if [ -f grype-report.json ]; then
          CRITICAL=$(grep -o '"severity":"Critical"' grype-report.json | wc -l || echo "0")
          HIGH=$(grep -o '"severity":"High"' grype-report.json | wc -l || echo "0")
          MEDIUM=$(grep -o '"severity":"Medium"' grype-report.json | wc -l || echo "0")
          
          echo "CVE Results:"
          echo "  Critical: $CRITICAL"
          echo "  High: $HIGH"
          echo "  Medium: $MEDIUM"
        fi
      
  post_build:
    commands:
      - echo CVE analysis completed on `date`
      - echo Uploading reports to S3...
      - aws s3 cp grype-report.json s3://$REPORTS_BUCKET/code-quality-reports/$CODEBUILD_BUILD_NUMBER/grype-cve.json --region eu-west-3 || true
      - aws s3 cp grype-report.txt s3://$REPORTS_BUCKET/code-quality-reports/$CODEBUILD_BUILD_NUMBER/grype-cve.txt --region eu-west-3 || true

artifacts:
  files:
    - grype-report.json
    - grype-report.txt

cache:
  paths:
    - '/root/.cache/grype/**/*'
