package com.social.platform.SocialMediaAPI.service;

import com.social.platform.SocialMediaAPI.entity.Comments;
import com.social.platform.SocialMediaAPI.repository.CommentsRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

import java.util.UUID;

/**
 * Service class for Comments entity
 * Generated by MDE Backend Generator
 */
@Service
@Transactional
public class CommentsService {

    private final CommentsRepository repository;

    public CommentsService(CommentsRepository repository) {
        this.repository = repository;
    }

    /**
     * Create a new Comments
     */
    public Comments create(Comments entity) {
        return repository.save(entity);
    }

    /**
     * Find Comments by ID
     */
    public Optional<Comments> findById(UUID id) {
        return repository.findById(id);
    }

    /**
     * Get all Comments entities
     */
    public List<Comments> findAll() {
        return repository.findAll();
    }

    /**
     * Update an existing Comments
     */
    public Comments update(UUID id, Comments entity) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("Comments not found with id: " + id);
        }
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete Comments by ID
     */
    public void delete(UUID id) {
        repository.deleteById(id);
    }

    /**
     * Check if Comments exists by ID
     */
    public boolean exists(UUID id) {
        return repository.existsById(id);
    }
}
