package com.social.platform.SocialMediaAPI.service;

import com.social.platform.SocialMediaAPI.entity.DirectMessages;
import com.social.platform.SocialMediaAPI.repository.DirectMessagesRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

import java.util.UUID;

/**
 * Service class for DirectMessages entity
 * Generated by MDE Backend Generator
 */
@Service
@Transactional
public class DirectMessagesService {

    private final DirectMessagesRepository repository;

    public DirectMessagesService(DirectMessagesRepository repository) {
        this.repository = repository;
    }

    /**
     * Create a new DirectMessages
     */
    public DirectMessages create(DirectMessages entity) {
        return repository.save(entity);
    }

    /**
     * Find DirectMessages by ID
     */
    public Optional<DirectMessages> findById(UUID id) {
        return repository.findById(id);
    }

    /**
     * Get all DirectMessages entities
     */
    public List<DirectMessages> findAll() {
        return repository.findAll();
    }

    /**
     * Update an existing DirectMessages
     */
    public DirectMessages update(UUID id, DirectMessages entity) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("DirectMessages not found with id: " + id);
        }
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete DirectMessages by ID
     */
    public void delete(UUID id) {
        repository.deleteById(id);
    }

    /**
     * Check if DirectMessages exists by ID
     */
    public boolean exists(UUID id) {
        return repository.existsById(id);
    }
}
