package com.social.platform.SocialMediaAPI.service;

import com.social.platform.SocialMediaAPI.entity.Hashtags;
import com.social.platform.SocialMediaAPI.repository.HashtagsRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

import java.util.UUID;

/**
 * Service class for Hashtags entity
 * Generated by MDE Backend Generator
 */
@Service
@Transactional
public class HashtagsService {

    private final HashtagsRepository repository;

    public HashtagsService(HashtagsRepository repository) {
        this.repository = repository;
    }

    /**
     * Create a new Hashtags
     */
    public Hashtags create(Hashtags entity) {
        return repository.save(entity);
    }

    /**
     * Find Hashtags by ID
     */
    public Optional<Hashtags> findById(UUID id) {
        return repository.findById(id);
    }

    /**
     * Get all Hashtags entities
     */
    public List<Hashtags> findAll() {
        return repository.findAll();
    }

    /**
     * Update an existing Hashtags
     */
    public Hashtags update(UUID id, Hashtags entity) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("Hashtags not found with id: " + id);
        }
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete Hashtags by ID
     */
    public void delete(UUID id) {
        repository.deleteById(id);
    }

    /**
     * Check if Hashtags exists by ID
     */
    public boolean exists(UUID id) {
        return repository.existsById(id);
    }
}
