package com.social.platform.SocialMediaAPI.service;

import com.social.platform.SocialMediaAPI.entity.Likes;
import com.social.platform.SocialMediaAPI.repository.LikesRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

import java.util.UUID;

/**
 * Service class for Likes entity
 * Generated by MDE Backend Generator
 */
@Service
@Transactional
public class LikesService {

    private final LikesRepository repository;

    public LikesService(LikesRepository repository) {
        this.repository = repository;
    }

    /**
     * Create a new Likes
     */
    public Likes create(Likes entity) {
        return repository.save(entity);
    }

    /**
     * Find Likes by ID
     */
    public Optional<Likes> findById(UUID id) {
        return repository.findById(id);
    }

    /**
     * Get all Likes entities
     */
    public List<Likes> findAll() {
        return repository.findAll();
    }

    /**
     * Update an existing Likes
     */
    public Likes update(UUID id, Likes entity) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("Likes not found with id: " + id);
        }
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete Likes by ID
     */
    public void delete(UUID id) {
        repository.deleteById(id);
    }

    /**
     * Check if Likes exists by ID
     */
    public boolean exists(UUID id) {
        return repository.existsById(id);
    }
}
