package com.social.platform.SocialMediaAPI.service;

import com.social.platform.SocialMediaAPI.entity.Notifications;
import com.social.platform.SocialMediaAPI.repository.NotificationsRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

import java.util.UUID;

/**
 * Service class for Notifications entity
 * Generated by MDE Backend Generator
 */
@Service
@Transactional
public class NotificationsService {

    private final NotificationsRepository repository;

    public NotificationsService(NotificationsRepository repository) {
        this.repository = repository;
    }

    /**
     * Create a new Notifications
     */
    public Notifications create(Notifications entity) {
        return repository.save(entity);
    }

    /**
     * Find Notifications by ID
     */
    public Optional<Notifications> findById(UUID id) {
        return repository.findById(id);
    }

    /**
     * Get all Notifications entities
     */
    public List<Notifications> findAll() {
        return repository.findAll();
    }

    /**
     * Update an existing Notifications
     */
    public Notifications update(UUID id, Notifications entity) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("Notifications not found with id: " + id);
        }
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete Notifications by ID
     */
    public void delete(UUID id) {
        repository.deleteById(id);
    }

    /**
     * Check if Notifications exists by ID
     */
    public boolean exists(UUID id) {
        return repository.existsById(id);
    }
}
