package com.social.platform.SocialMediaAPI.service;

import com.social.platform.SocialMediaAPI.entity.PostHashtags;
import com.social.platform.SocialMediaAPI.repository.PostHashtagsRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

import java.util.UUID;

/**
 * Service class for PostHashtags entity
 * Generated by MDE Backend Generator
 */
@Service
@Transactional
public class PostHashtagsService {

    private final PostHashtagsRepository repository;

    public PostHashtagsService(PostHashtagsRepository repository) {
        this.repository = repository;
    }

    /**
     * Create a new PostHashtags
     */
    public PostHashtags create(PostHashtags entity) {
        return repository.save(entity);
    }

    /**
     * Find PostHashtags by ID
     */
    public Optional<PostHashtags> findById(UUID id) {
        return repository.findById(id);
    }

    /**
     * Get all PostHashtags entities
     */
    public List<PostHashtags> findAll() {
        return repository.findAll();
    }

    /**
     * Update an existing PostHashtags
     */
    public PostHashtags update(UUID id, PostHashtags entity) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("PostHashtags not found with id: " + id);
        }
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete PostHashtags by ID
     */
    public void delete(UUID id) {
        repository.deleteById(id);
    }

    /**
     * Check if PostHashtags exists by ID
     */
    public boolean exists(UUID id) {
        return repository.existsById(id);
    }
}
