package com.social.platform.SocialMediaAPI.service;

import com.social.platform.SocialMediaAPI.entity.Posts;
import com.social.platform.SocialMediaAPI.repository.PostsRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

import java.util.UUID;

/**
 * Service class for Posts entity
 * Generated by MDE Backend Generator
 */
@Service
@Transactional
public class PostsService {

    private final PostsRepository repository;

    public PostsService(PostsRepository repository) {
        this.repository = repository;
    }

    /**
     * Create a new Posts
     */
    public Posts create(Posts entity) {
        return repository.save(entity);
    }

    /**
     * Find Posts by ID
     */
    public Optional<Posts> findById(UUID id) {
        return repository.findById(id);
    }

    /**
     * Get all Posts entities
     */
    public List<Posts> findAll() {
        return repository.findAll();
    }

    /**
     * Update an existing Posts
     */
    public Posts update(UUID id, Posts entity) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("Posts not found with id: " + id);
        }
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete Posts by ID
     */
    public void delete(UUID id) {
        repository.deleteById(id);
    }

    /**
     * Check if Posts exists by ID
     */
    public boolean exists(UUID id) {
        return repository.existsById(id);
    }
}
