package com.social.platform.SocialMediaAPI.service;

import com.social.platform.SocialMediaAPI.entity.UserFollows;
import com.social.platform.SocialMediaAPI.repository.UserFollowsRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

import java.util.UUID;

/**
 * Service class for UserFollows entity
 * Generated by MDE Backend Generator
 */
@Service
@Transactional
public class UserFollowsService {

    private final UserFollowsRepository repository;

    public UserFollowsService(UserFollowsRepository repository) {
        this.repository = repository;
    }

    /**
     * Create a new UserFollows
     */
    public UserFollows create(UserFollows entity) {
        return repository.save(entity);
    }

    /**
     * Find UserFollows by ID
     */
    public Optional<UserFollows> findById(UUID id) {
        return repository.findById(id);
    }

    /**
     * Get all UserFollows entities
     */
    public List<UserFollows> findAll() {
        return repository.findAll();
    }

    /**
     * Update an existing UserFollows
     */
    public UserFollows update(UUID id, UserFollows entity) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("UserFollows not found with id: " + id);
        }
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete UserFollows by ID
     */
    public void delete(UUID id) {
        repository.deleteById(id);
    }

    /**
     * Check if UserFollows exists by ID
     */
    public boolean exists(UUID id) {
        return repository.existsById(id);
    }
}
