package com.social.platform.SocialMediaAPI.service;

import com.social.platform.SocialMediaAPI.entity.Users;
import com.social.platform.SocialMediaAPI.repository.UsersRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

import java.util.UUID;

/**
 * Service class for Users entity
 * Generated by MDE Backend Generator
 */
@Service
@Transactional
public class UsersService {

    private final UsersRepository repository;

    public UsersService(UsersRepository repository) {
        this.repository = repository;
    }

    /**
     * Create a new Users
     */
    public Users create(Users entity) {
        return repository.save(entity);
    }

    /**
     * Find Users by ID
     */
    public Optional<Users> findById(UUID id) {
        return repository.findById(id);
    }

    /**
     * Get all Users entities
     */
    public List<Users> findAll() {
        return repository.findAll();
    }

    /**
     * Update an existing Users
     */
    public Users update(UUID id, Users entity) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("Users not found with id: " + id);
        }
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete Users by ID
     */
    public void delete(UUID id) {
        repository.deleteById(id);
    }

    /**
     * Check if Users exists by ID
     */
    public boolean exists(UUID id) {
        return repository.existsById(id);
    }
}
