package com.social.platform.SocialMediaAPI.repository;

import com.social.platform.SocialMediaAPI.entity.Comments;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.UUID;

/**
 * Repository interface for Comments entity
 * Generated by MDE Backend Generator
 */
@Repository
public interface CommentsRepository extends JpaRepository<Comments, UUID> {
    
    // Custom query methods can be added here
    
}
