package com.social.platform.SocialMediaAPI.repository;

import com.social.platform.SocialMediaAPI.entity.Hashtags;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.UUID;

/**
 * Repository interface for Hashtags entity
 * Generated by MDE Backend Generator
 */
@Repository
public interface HashtagsRepository extends JpaRepository<Hashtags, UUID> {
    
    // Custom query methods can be added here
    
}
