package com.social.platform.SocialMediaAPI.repository;

import com.social.platform.SocialMediaAPI.entity.Likes;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.UUID;

/**
 * Repository interface for Likes entity
 * Generated by MDE Backend Generator
 */
@Repository
public interface LikesRepository extends JpaRepository<Likes, UUID> {
    
    // Custom query methods can be added here
    
}
