package com.social.platform.SocialMediaAPI.repository;

import com.social.platform.SocialMediaAPI.entity.Notifications;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.UUID;

/**
 * Repository interface for Notifications entity
 * Generated by MDE Backend Generator
 */
@Repository
public interface NotificationsRepository extends JpaRepository<Notifications, UUID> {
    
    // Custom query methods can be added here
    
}
