package com.social.platform.SocialMediaAPI.repository;

import com.social.platform.SocialMediaAPI.entity.Posts;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.UUID;

/**
 * Repository interface for Posts entity
 * Generated by MDE Backend Generator
 */
@Repository
public interface PostsRepository extends JpaRepository<Posts, UUID> {
    
    // Custom query methods can be added here
    
}
