package com.social.platform.SocialMediaAPI.repository;

import com.social.platform.SocialMediaAPI.entity.PostHashtags;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.UUID;

/**
 * Repository interface for PostHashtags entity
 * Generated by MDE Backend Generator
 */
@Repository
public interface PostHashtagsRepository extends JpaRepository<PostHashtags, UUID> {
    
    // Custom query methods can be added here
    
}
