package com.social.platform.SocialMediaAPI.repository;

import com.social.platform.SocialMediaAPI.entity.Users;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.UUID;

/**
 * Repository interface for Users entity
 * Generated by MDE Backend Generator
 */
@Repository
public interface UsersRepository extends JpaRepository<Users, UUID> {
    
    // Custom query methods can be added here
    
}
