package com.social.platform.SocialMediaAPI.repository;

import com.social.platform.SocialMediaAPI.entity.UserFollows;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.UUID;

/**
 * Repository interface for UserFollows entity
 * Generated by MDE Backend Generator
 */
@Repository
public interface UserFollowsRepository extends JpaRepository<UserFollows, UUID> {
    
    // Custom query methods can be added here
    
}
