package com.social.platform.SocialMediaAPI.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.ToString;
import lombok.EqualsAndHashCode;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;
import java.util.List;
import java.util.Set;

/**
 * Entity class for posts table
 * Generated by MDE Backend Generator
 */
@Entity
@Table(name = "posts")
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString(onlyExplicitlyIncluded = true)
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class Posts implements Serializable {

    @ToString.Include
    @EqualsAndHashCode.Include
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", nullable = false)
    private UUID id;
    
    @Column(name = "content", nullable = false)
    private String content;
    
    @Column(name = "image_url", nullable = true)
    private String imageUrl;
    
    @Column(name = "like_count", nullable = true)
    private Integer likeCount;
    
    @Column(name = "comment_count", nullable = true)
    private Integer commentCount;
    
    @CreatedDate
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;
    
    @LastModifiedDate
    @Column(name = "updated_at", nullable = true)
    private LocalDateTime updatedAt;
    

    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)    @JoinColumn(name = "user_id")
    private Users user;
    
    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "post")    private List<Comments> postCommentsList;
    
    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "post")    private List<Likes> postLikesList;
    
    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "post")    private List<PostHashtags> postPostHashtagsList;
    
}
