package com.social.platform.SocialMediaAPI.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.ToString;
import lombok.EqualsAndHashCode;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;
import java.util.List;
import java.util.Set;

/**
 * Entity class for users table
 * Generated by MDE Backend Generator
 */
@Entity
@Table(name = "users")
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString(onlyExplicitlyIncluded = true)
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class Users implements Serializable {

    @ToString.Include
    @EqualsAndHashCode.Include
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", nullable = false)
    private UUID id;
    
    @Column(name = "username", nullable = false, unique = true)
    private String username;
    
    @Column(name = "email", nullable = false, unique = true)
    private String email;
    
    @Column(name = "full_name", nullable = true)
    private String fullName;
    
    @Column(name = "bio", nullable = true)
    private String bio;
    
    @Column(name = "profile_picture_url", nullable = true)
    private String profilePictureUrl;
    
    @Column(name = "is_verified", nullable = true)
    private Boolean isVerified;
    
    @CreatedDate
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;
    
    @LastModifiedDate
    @Column(name = "updated_at", nullable = true)
    private LocalDateTime updatedAt;
    

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "follower")    private List<UserFollows> followerUserFollowsList;
    
    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "following")    private List<UserFollows> followingUserFollowsList;
    
    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")    private List<Posts> userPostsList;
    
    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")    private List<Comments> userCommentsList;
    
    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")    private List<Likes> userLikesList;
    
    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sender")    private List<DirectMessages> senderDirectMessagesList;
    
    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "recipient")    private List<DirectMessages> recipientDirectMessagesList;
    
    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")    private List<Notifications> userNotificationsList;
    
}
